baseurl = ""
title = "jayllyz"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Jayllyz"

[params]
    author = "Antony David"
    info = "Student at ESIEA"
    description = "Antony David's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/JayPdp.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jayllyz/"
[[params.social]]
    name = "Gitlab"
    icon = "fas fa-tv fa-2x"
    weight = 2
    url = "https://www.tvtime.com/fr/user/16702193/profile"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/jayllyz"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
	
