baseURL = "https://jayllyz.netlify.app/"
title = "jayllyz"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true


[params]
author = "Antony David"
description = "Antony David's personal website"
keywords = "blog,developer,personal"
info = ["Student at ESGI"]
avatarURL = "images/jaypdp.png"

dateFormat = "January 2, 2006"
hideFooter = true
hideCredits = true
hideCopyright = true
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"

rtl = false

colorScheme = "light"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = true
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []




[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/jayllyz/"


[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 4
url = "https://twitter.com/jayllyz/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/antony-david-8222161a0/"


[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Survive the tempest"
weight = 2
url = "svt/"

[[languages.en.menu.main]]
name = "Well Eat"
weight = 1
url = "welleat/"

[[languages.en.menu.main]]
name = "CV"
weight = 1
url = "https://jayllyz.github.io/online-cv/"

[[languages.en.menu.main]]
name = "About"
weight = 3
url = "about/"

