baseurl = ""
title = "jayllyz"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Jayllyz"

[params]
    author = "Antony David"
    info = "Student at ESIEA"
    description = "Antony David's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/JayPdp.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

	enableTwemoji = true

	colorsheme = "auto"
    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
	
    # Custom CSS
    customCSS = ["custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/jayllyz/"
[[params.social]]
    name = "Linkedin"
    icon = "fa fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/antony-david-8222161a0/"
[[params.social]]
    name = "Twitter"
    icon = "fb fa-twitter fa"
    weight = 3
    url = "https://twitter.com/jayllyz"

# Menu links
[[menu.main]]
    name = "Well Eat"
    weight = 1
    url = "/welleat/"
[[menu.main]]
    name = "Survive the tempest"
    weight = 2
    url  = "/svt/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
	
 